services:
  svr_n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    environment:
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - N8N_EDITOR_BASE_URL=${EXTERNAL_IP}
      - WEBHOOK_URL=${EXTERNAL_IP}
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
    ports:
      - "5678:5678"
    volumes:
      - /root/n8n:/home/node/.n8n
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    hostname: ngrok
    command: ["start", "--all", "--config", "/root/ngrok.yml"]
    volumes:
      - ./ngrok.yml:/root/ngrok.yml
    networks: ['demo']
    restart: unless-stopped
    ports:
      - 4040:4040
